-- AlterTable
ALTER TABLE "Post" ADD COLUMN "mediaCropY" DOUBLE PRECISION;
ALTER TABLE "Post" ADD COLUMN "mediaAspectRatio" TEXT;
ALTER TABLE "Post" ADD COLUMN "sortOrder" INTEGER NOT NULL DEFAULT 0;
